# Generated by Django 3.2.4 on 2021-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_carrito_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carrito'},
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(to='producto.Producto'),
        ),
    ]
