# Generated by Django 3.2.4 on 2021-07-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
