# Generated by Django 3.2.4 on 2021-07-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='cosmeticos', max_length=100, verbose_name='Nombre de la categoria'),
        ),
    ]
