# Generated by Django 3.2.4 on 2021-07-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_auto_20210705_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(to='producto.Producto'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
