# Generated by Django 3.2.4 on 2021-07-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_auto_20210706_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='items',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
