# Generated by Django 3.2.4 on 2021-07-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(null=True, to='producto.Producto'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
    ]
