# Generated by Django 3.2.4 on 2021-07-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0015_auto_20210706_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=255, verbose_name='Descripción'),
        ),
    ]
