# Generated by Django 3.2.4 on 2021-07-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_moderador',
            field=models.BooleanField(default=False),
        ),
    ]
